version: "3"

services:

  shopware:
    # use either tag "latest" or any other version like "6.5.3.0", ...
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "80:80"
      - "3308:3308"
      - "22:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=1
      # default = latest PHP, optional = specific version
      - PHP_VERSION=8.3

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false