
services:
###> shopware/core ###
  database:
    ports:
      - "3306"
###< shopware/core ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> shopware/elasticsearch ###
  opensearch:
    ports:
      - "9200"
###< shopware/elasticsearch ###
